// -----------------------------------------------------------------------------
// SPDX-FileNotice: KuiperZone.Marklet - Local AI Client
// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: © 2025-2026 Andrew Thomas <kuiperzone@users.noreply.github.com>
// SPDX-ProjectHomePage: https://kuiper.zone/marklet-ai/
// SPDX-FileType: Source
// SPDX-FileComment: This is NOT AI generated source code but was created with human thinking and effort.
// -----------------------------------------------------------------------------

// Marklet is free software: you can redistribute it and/or modify it under
// the terms of the GNU Affero General Public License as published by the Free Software
// Foundation, version 3 of the License only.
//
// Marklet is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License along
// with Marklet. If not, see <https://www.gnu.org/licenses/>.

namespace KuiperZone.Marklet.Stack.Garden;

/// <summary>
/// Kind values pertaining to <see cref="GardenLeaf"/>.
/// </summary>
/// <remarks>
/// Integer values are written to storage and must not change.
/// </remarks>
public enum LeafKind : byte
{
    /// <summary>
    /// None (invalid).
    /// </summary>
    None = 0,

    /// <summary>
    /// User message.
    /// </summary>
    User = 1,

    /// <summary>
    /// Assistant message.
    /// </summary>
    Assistant = 2,

    /// <summary>
    /// Display information only. Not persistant or to be interpreted by the model.
    /// </summary>
    DisplayMessage = 200,

    /// <summary>
    /// Display error only. Not persistant or to be interpreted by the model.
    /// </summary>
    DisplayError = 201,
}

/// <summary>
/// Extension methods.
/// </summary>
public static partial class HelperExt
{
    /// <summary>
    /// Returns whether the leaf is to be to written to the database.
    /// </summary>
    public static bool IsPersistant(this LeafKind src)
    {
        return src == LeafKind.User || src == LeafKind.Assistant;
    }

    /// <summary>
    /// Returns whether content is generated by or a model.
    /// </summary>
    public static bool HasModel(this LeafKind src)
    {
        return src == LeafKind.Assistant;
    }

    /// <summary>
    /// Returns a default entity name such as "User", "Assistant" or null.
    /// </summary>
    public static string? DefaultEntity(this LeafKind src)
    {
        switch (src)
        {
            case LeafKind.User:
                return "User";
            case LeafKind.Assistant:
                return "Assistant";
            default:
                return null;
        }
    }

    /// <summary>
    /// Returns whether the leaf content is nominally show to the user.
    /// </summary>
    public static bool IsShown(this LeafKind src)
    {
        return src != LeafKind.None;
    }

    /// <summary>
    /// Returns whether display fully parses inline markup.
    /// </summary>
    public static bool HasInlineMarkup(this LeafKind src)
    {
        return src == LeafKind.Assistant || src == LeafKind.DisplayMessage;
    }

    /// <summary>
    /// Ensure underlying value is legal.
    /// </summary>
    public static bool IsLegal(this LeafKind src)
    {
        switch (src)
        {
            case LeafKind.User:
            case LeafKind.Assistant:
            case LeafKind.DisplayMessage:
            case LeafKind.DisplayError:
                return true;
            default:
                return false;
        }
    }
}